version: '3.9'

services:
  broker:
    image: eclipse-mosquitto
    user: mosquitto
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_data:/mosquitto/log
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./password.txt:/mosquitto/config/password.txt
      - ./certs:/certs
    ports:
      - '1884:1884'


volumes:
  mosquitto_data: